### PR TITLE
Refactoring of systemd service implementation

### PR DESCRIPTION
**Pull request by nkvr62**
This is a PR to address the concern raised here: [https://github.com/dasource/partyman/issues/31](url)
Overview of changes:

- stop relying on the particld.service file in the main particl-core repo by creating a bespoke particld.service file in the partyman repo
- Implement the particld.service as a "user service" (--user).  One benefit here is that the service is now user-agnostic.  I removed the check for user "particl" in the particld.service install subroutine. (though I did leave the warning to prefer running at user "particl")
- refactor how partyman starts and stops particld so that it first attempts to use the particld.service.  if the service file doesnt exist it should revert back to the original method or starting/stopping
- update the README to include a couple of dependencies that I have found necessary to make partyman work (Debian 10)
- Lastly I made a small change to fix an error that is thrown when $PARTYD_PID does not exist (~line 1374) and unsets the variable if $PARTYD_HASPID does not equal 1.

I tested this with a few different setups and it seems to function as intended, but some other testing would be appreciated.  Most notably is that I did not do robust testing on how this would play with existing installs (because of the systemd fallback it should be ok)

Lastly, I am not a professional developer, so I would appreciate any feedback on how to improve any future PRs!

### CODE REVIEW

**Review by tecnovert — CHANGES_REQUESTED** [review]
I've tested on my existing system running partyman.

Before installing the systemd files restarting looks as if it fails although it does work.
Can a message be added to the fallback path to let the user know it's retrying with a different method?
```
restart particld? [y/N] y
 --> Stopping particld. Please wait...Failed to stop particld.service: Unit particld.service not loaded.
 done!
 --> Starting particld... Failed to start particld.service: Unit particld.service not found.
 done!
 --> Waiting for particld to respond... .... done!
```

Is the cp -r flag necessary to install particld.service?

After installing the systemd service it all seems to work:
```
mkdir -p /home/$USER/.config/systemd/user/
cp -f ~/partyman/particld.service /home/$USER/.config/systemd/user/;
systemctl --user daemon-reload
systemctl --user enable particld
```

To get particld to start after a reboot I had to run
```
sudo loginctl enable-linger $USER
```

And change `WantedBy=multi-user.target` -> `WantedBy=default.target` in particld.service 
and reinstall  with:
```
systemctl --user daemon-reload
systemctl --user disable particld
systemctl --user enable particld
```

I tried updating the particld.service file:
https://gist.github.com/tecnovert/5b0d7bb9fcdb20c78485da4f2a2f9f59

**Comment by nkvr62** [comment]
Ok this is ready for another look!

**Review by tecnovert — APPROVED** [review]
Tested on a new install.
Everything seems to work.

**Comment by dasource** [comment]
Hi @nkvr62 

I have done more testing on this and the one use case which does not seem to be addressed is an existing install.

I was thinking maybe we could catch this on the "upgrade/reinstall" and if the old service is present remove it and add the new one, if the service is not present then add new one.

Thank you.

**Comment by dasource** [comment]
Have merged as-is since it does not interfere with existing installations.

**Pull request merged**
